# Generated by Django 4.2.19 on 2025-05-09 00:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricula", models.CharField(max_length=20)),
                ("nome", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "url_consulta",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("status_atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_consulta",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(max_length=100)),
                ("detalhes", models.TextField(blank=True, null=True)),
                (
                    "url_consulta",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="monitor.pessoa",
                    ),
                ),
            ],
        ),
    ]
