# Generated by Django 5.2 on 2025-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CO_MAT', models.DecimalField(decimal_places=0, max_digits=10)),
                ('DE_MAT', models.CharField(max_length=4000)),
                ('QT_SALDO_ATU', models.IntegerField()),
            ],
        ),
    ]
