# Generated by Django 3.2.25 on 2025-07-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaOficial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('CO_MAT', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('QT_SALDO_MES_ANT', models.DecimalField(decimal_places=0, max_digits=7)),
                ('VL_MES_ANT', models.DecimalField(decimal_places=2, max_digits=13)),
                ('QT_ENTR_MES', models.DecimalField(decimal_places=0, max_digits=7)),
                ('VL_ENTR_MES', models.DecimalField(decimal_places=2, max_digits=13)),
                ('QT_SAIDA_MES_MAT', models.DecimalField(decimal_places=0, max_digits=7)),
                ('VL_SAIDA_MES', models.DecimalField(decimal_places=2, max_digits=13)),
                ('QT_SALDO_ATU', models.DecimalField(decimal_places=0, max_digits=7)),
                ('VL_ATU', models.DecimalField(decimal_places=2, max_digits=13)),
                ('QT_SALDO_ANO_ANT', models.DecimalField(decimal_places=0, max_digits=7)),
                ('VL_ANO_ANT', models.DecimalField(decimal_places=2, max_digits=13)),
                ('QT_ENTR_ATE_MES_ANT', models.DecimalField(decimal_places=0, max_digits=7)),
                ('VL_ENTR_ATE_MES_ANT', models.DecimalField(decimal_places=2, max_digits=13)),
                ('QT_SAIDA_ATE_MES_ANT', models.DecimalField(decimal_places=0, max_digits=7)),
                ('VL_SAIDA_ATE_MES_ANT', models.DecimalField(decimal_places=2, max_digits=13)),
                ('QT_RESERVADA', models.DecimalField(decimal_places=0, max_digits=7)),
                ('QT_ESTQ_MAX', models.DecimalField(decimal_places=0, max_digits=7)),
                ('QT_ESTQ_MIN', models.DecimalField(decimal_places=0, max_digits=7)),
                ('TI_FINALIDADE', models.DecimalField(decimal_places=0, max_digits=2)),
                ('NU_PED_COMPRA', models.DecimalField(decimal_places=0, max_digits=8)),
                ('QT_MEDIA_CONSUMO', models.DecimalField(decimal_places=0, max_digits=7)),
                ('QT_MES_AQUIS', models.DecimalField(decimal_places=0, max_digits=2)),
                ('QT_INTERVALO_AQUIS', models.DecimalField(decimal_places=0, max_digits=7)),
                ('QT_FRACAO_AQUIS', models.DecimalField(decimal_places=3, max_digits=5)),
                ('FG_SUPRIM_AUTOM', models.CharField(max_length=1)),
                ('FG_PED_COMPRA', models.CharField(max_length=1)),
                ('CO_UNID_MEDIDA', models.CharField(max_length=3)),
                ('CO_UNID_COMPRA', models.CharField(max_length=3)),
                ('CO_OPERACAO', models.DecimalField(decimal_places=0, max_digits=1)),
                ('VL_OPERADOR', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DE_MAT', models.TextField()),
                ('DE_COMPRA', models.TextField()),
                ('DE_COMPRA_COMPL', models.TextField()),
                ('DT_PED_COMPRA', models.DateField()),
                ('FG_ANALISADO', models.CharField(max_length=1)),
                ('FG_DESUSO', models.CharField(max_length=1)),
                ('QT_MEDIA_CONSUMO_2', models.DecimalField(decimal_places=0, max_digits=7)),
                ('QT_SALDO_VALIDADE', models.DecimalField(decimal_places=0, max_digits=7)),
                ('CO_MAT_SIASG', models.CharField(max_length=9)),
                ('DE_COMPRA_CLOB', models.TextField()),
                ('FG_SUSTENTAVEL', models.CharField(default='N', max_length=1)),
                ('FG_CARTUCHO', models.CharField(default='N', max_length=1)),
                ('FG_CONSUMO_IMEDIATO', models.CharField(default='N', max_length=1)),
                ('IMAGEM_MATERIAL', models.BinaryField()),
            ],
            options={
                'db_table': 'MATERIAL',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DatabaseTeste',
        ),
    ]
