# Generated by Django 3.2.25 on 2025-07-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaOficial', '0002_auto_20250717_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialValidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sima_co_mat', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sima_co_lote', models.CharField(max_length=20)),
                ('sima_dt_validade', models.DateField()),
                ('sima_qtd_material', models.DecimalField(decimal_places=0, max_digits=7)),
            ],
            options={
                'db_table': 'MATERIAL_VALIDADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentoSaidaDefinitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_mat', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nu_req', models.DecimalField(decimal_places=0, max_digits=9)),
                ('co_lota', models.DecimalField(decimal_places=0, max_digits=6)),
                ('dt_baixa_req', models.DateField()),
                ('qt_entg_req', models.DecimalField(decimal_places=0, max_digits=7)),
                ('vl_tot_req', models.DecimalField(decimal_places=2, max_digits=13)),
                ('nu_matr_reqte', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'MOVIMENTO_SAIDA_DEFINITIVO',
                'managed': False,
            },
        ),
    ]
